const CARDS = {
	"troops":{ #name (japanese), color, value
  "red1": ["散兵", "red", 1],
  "red2": ["軽装歩兵", "red", 2],
  "red3": ["投槍兵", "red", 3],
  "red4": ["重装歩兵", "red", 4],
  "red5": ["重装槍兵", "red", 5],
  "red6": ["親衛歩兵", "red", 6],
  "red7": ["軽騎兵", "red", 7],
  "red8": ["重騎兵", "red", 8],
  "red9": ["二輪戦車", "red", 9],
  "red10": ["戦象", "red", 10],

  "orange1": ["散兵", "orange", 1],
  "orange2": ["軽装歩兵", "orange", 2],
  "orange3": ["投槍兵", "orange", 3],
  "orange4": ["重装歩兵", "orange", 4],
  "orange5": ["重装槍兵", "orange", 5],
  "orange6": ["親衛歩兵", "orange", 6],
  "orange7": ["軽騎兵", "orange", 7],
  "orange8": ["重騎兵", "orange", 8],
  "orange9": ["二輪戦車", "orange", 9],
  "orange10": ["戦象", "orange", 10],

  "yellow1": ["散兵", "yellow", 1],
  "yellow2": ["軽装歩兵", "yellow", 2],
  "yellow3": ["投槍兵", "yellow", 3],
  "yellow4": ["重装歩兵", "yellow", 4],
  "yellow5": ["重装槍兵", "yellow", 5],
  "yellow6": ["親衛歩兵", "yellow", 6],
  "yellow7": ["軽騎兵", "yellow", 7],
  "yellow8": ["重騎兵", "yellow", 8],
  "yellow9": ["二輪戦車", "yellow", 9],
  "yellow10": ["戦象", "yellow", 10],

  "green1": ["散兵", "green", 1],
  "green2": ["軽装歩兵", "green", 2],
  "green3": ["投槍兵", "green", 3],
  "green4": ["重装歩兵", "green", 4],
  "green5": ["重装槍兵", "green", 5],
  "green6": ["親衛歩兵", "green", 6],
  "green7": ["軽騎兵", "green", 7],
  "green8": ["重騎兵", "green", 8],
  "green9": ["二輪戦車", "green", 9],
  "green10": ["戦象", "green", 10],

  "blue1": ["散兵", "blue", 1],
  "blue2": ["軽装歩兵", "blue", 2],
  "blue3": ["投槍兵", "blue", 3],
  "blue4": ["重装歩兵", "blue", 4],
  "blue5": ["重装槍兵", "blue", 5],
  "blue6": ["親衛歩兵", "blue", 6],
  "blue7": ["軽騎兵", "blue", 7],
  "blue8": ["重騎兵", "blue", 8],
  "blue9": ["二輪戦車", "blue", 9],
  "blue10": ["戦象", "blue", 10],

  "purple1": ["散兵", "purple", 1],
  "purple2": ["軽装歩兵", "purple", 2],
  "purple3": ["投槍兵", "purple", 3],
  "purple4": ["重装歩兵", "purple", 4],
  "purple5": ["重装槍兵", "purple", 5],
  "purple6": ["親衛歩兵", "purple", 6],
  "purple7": ["軽騎兵", "purple", 7],
  "purple8": ["重騎兵", "purple", 8],
  "purple9": ["二輪戦車", "purple", 9],
  "purple10": ["戦象", "purple", 10]
},
	"tactics":{ #name (japanese), description(?)
		"alexander": ["アレキサンダー", "morale"],
		"darius": ["ダリウス", "morale"],
		"companioncavalry": ["援軍騎兵", "morale"],
		"shieldbearers": ["盾", "morale"],
		"fog":["霧", "environment"],
		"mud":["泥濘", "environment"],
		"scout": ["偵察", "guile"],
		"redeploy": ["配置転換", "guile"],
		"deserter": ["脱走", "guile"],
		"traitor": ["裏切り", "guile"]
		
	}
	
}
